### ISSUE TITLE
Small amount of lag

### ISSUE THREAD

**Issue by NicoNekoDev** [Rosstail/Karma#16]
https://timings.aikar.co/?id=4be7f06d7f694ca096596520fee0625d#plugins

There is a little lag footprint your plugin does, but I think it's a bit too much for what the plugin does.

**Comment by Rosstail** [comment]
Hi there. Maybe the 1.10.2 will fix your problem.
[try this](https://www.spigotmc.org/resources/karma.76077/update?update=444131)

**Comment by NicoNekoDev** [comment]
Unsure if it fixed the problem, I have to run it for some time, but... meanwhile a new error appeared:
https://paste.md-5.net/relagoribu.pl

**Comment by Rosstail** [comment]
Alright, i'll remove this update asap and fix this, sorry for the inconvenience.

**Comment by NicoNekoDev** [comment]
You could also improve time complexity by calling playerList.values() and not playerList.keySet() and then playerList.get(player)

**Comment by Rosstail** [comment]
> You could also improve time complexity by calling playerList.values() and not playerList.keySet() and then playerList.get(player) Also, I'm unsure why you're using a date wrapper (Timestamp) as it could be slower that Date

It's my flaw actually, I don't really know what is the most optimized and I'm more with an objective of "I do what I want to with things I'm more comfortable with", so it can make no sense for higher-skilled devs ^^'.

**Comment by NicoNekoDev** [comment]
> > You could also improve time complexity by calling playerList.values() and not playerList.keySet() and then playerList.get(player) Also, I'm unsure why you're using a date wrapper (Timestamp) as it could be slower that Date
> 
> It's my flaw actually, I don't really know what is the most optimized and I'm more with an objective of "I do what I want to with things I'm more comfortable with", so it can make no sense for higher-skilled devs ^^'.
> 
> 

There is actually a lot of things that could be optimised. I'm still looking through the code. The most mind blowing thing is that you're using the database on sync.
I bet it won't cause any issues xD

**Comment by Rosstail** [comment]
> 

Not really. The database saves are async (Disconnection, save command, countdown...) unless the server closes (to save all data before the server closes), this one is fully sync. But maybe INSERTs and table creations, are not optimized. Little steps I guess XD
