### ISSUE TITLE
Suggestion: Make victim lose karma through a "killed-expression"

### ISSUE THREAD

**Issue by Shad0wolf0** [Rosstail/Karma#19]
Hi! I'm trying to make it so the victim loses karma as much as the killer gains karma. The scoring in the tier list isn't as flexible as I want it to be so I disabled it. Could you also make a '/karma top' to find top players?

**Comment by Rosstail** [comment]
Hi there !
At the moment there is no way to make the victim lose karma with expressions, but I could add it.

For the topscore, I am afraid I cannot do it (or at least right now) for some reasons, mainly because i don't really know how to handle this.

**Comment by Rosstail** [comment]
The scoreboard is finally behind added to the plugin upon 1.14.0

For the victim lose karma, you can use the kill-commands between tiers.
