### ISSUE TITLE
Placeholders not working?

### ISSUE THREAD

**Issue by ali-2500** [Rosstail/Karma#20]
I tried %karma_player_tier_short_display% and %karma_player_karma%  , it gave no response?

**Comment by Rosstail** [comment]
Hi there, can you give me precisions on how do you use these placeholders ? Like,on which plugin do you use it, commands, etc ?

**Comment by Rosstail** [comment]
This problem has been fix by itself after a restart and the short display placeholder is just colours by défaut in config.yml
