### ISSUE TITLE
Choice of the world

### ISSUE THREAD

**Issue by KingsRequin** [Rosstail/Karma#5]
Hello, I would like to know if it was possible to activate karma only on one world?

thank you !

**Comment by Rosstail** [comment]
Hi,

Lucky you, I just made this system for my other system. I'll add this system on the next update !

**Comment by KingsRequin** [comment]
yeah, thanks !

**Comment by Rosstail** [comment]
> yeah, thanks !

I just added the system but not added it in the actual plugin right now, I just have to repair another little thing before.

I think update the plugin wednesday.

**Comment by KingsRequin** [comment]
Okay,
I also wanted to ask if it was possible to add some things like As an addition of permission
Ex : `Karma.thug`
And change permission when players change karma


It could be used with plugins like: if the player does not have `karma.thug` then he cannot perform this action

It would be personally useful to me for the BetonQuest plugin

I don't know if something like this is possible

**Comment by Rosstail** [comment]
> Okay,
> I also wanted to ask if it was possible to add some things like As an addition of permission
> Ex : `Karma.thug`
> And change permission when players change karma
> 
> It could be used with plugins like: if the player does not have `karma.thug` then he cannot perform this action
> 
> It would be personally useful to me for the BetonQuest plugin
> 
> I don't know if something like this is possible

What do you mean by "action" ? 
or if i understand correctly, you mean change permission without command on tier change ? It is possible yes, but on per-world, then not server-wide, (technically possible, but I lack skill) '-'

**Comment by KingsRequin** [comment]
sorry I use google translate to express my ideas, it can be compl icated to understand  :/

What I mean is: If the player is at tier 1, then he has `karma.tier1`

If the player goes to tier 2 level then the authorization automatically goes to `karma.tier2`

**Comment by Rosstail** [comment]
I have added the world fight system. Be careful to update your config too !

[Update 1.5.1](https://www.spigotmc.org/resources/karma.76077/update?update=394676)

For the permissions, I'll see what I can do server-wide.

**Comment by KingsRequin** [comment]
Okay, thanks !

**Comment by Rosstail** [comment]
Hi. 

I'm actually in hollidays and unable to work on the plugin until some weeks.

The 1.5.5 will be out soon after, and it'll can help you to set permissions on tiers.

**Comment by KingsRequin** [comment]
ok, no problem, thanks!

**Comment by Rosstail** [comment]
Hi,

Without really solution to this, I can just suggest you to this way on every tiers you created (Adapt this to your permission plugin, I use PermissionEx as example) :

```yaml
    tier:
      ...
      join-commands:
        - "pex user %player% remove karma.*" #it removes all the karma.something permissions
        - "pex user %player% add karma.%karma_player_tier%" #add the karma.tier permission to the player depending of the tier.
```

Hope it helps you. I'll close the topic, if you need more thing or a rework on this subject, please ask by creating an other issue.
