### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GlobusOk** [Rosstail/Karma#8]
Hello.
I would like to clarify whether it is possible to display a list of players with negative and positive karma. I want to make 2 holograms with the top list.

**Comment by Rosstail** [comment]
Hi.
you can't do that at this moment because I didn't created this feature yet.

I can do it for online players, first provided only with PAPI placeholders (list and top/bottom list).

**Comment by GlobusOk** [comment]
This top would really help me. Thanks for your reply, I will look forward to further updates.

**Comment by Rosstail** [comment]
Hi. I'm actually in holidays. I'll add your suggestion on 1.5.5 version soon after my return.

**Comment by Rosstail** [comment]
Hi

Sorry for the delay. At this moment, my code is not really compatible with this, for performances reasons. i'll try to do this soon, but this is not guaranted.
